services:
  vote:
    image: rssureshkumar/voting-app-vote:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    networks:
      - backend

  result:
    image: rssureshkumar/voting-app-result:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5001:80"
    networks:
      - backend

  ui:
    image: rssureshkumar/voting-app-ui:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - frontend

  worker:
    image: rssureshkumar/voting-app-worker:latest
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    networks:
      - frontend
      - backend

  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - frontend
    volumes:
      - redis-data:/data

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: voteapp
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay

volumes:
  redis-data:
    driver: local
  db-data:
    driver: local
